### ISSUE TITLE
after 24 hour library show error

### ISSUE THREAD

**Issue by gillangit** [mimamch/wa-multi-session#29]
/opt/node_apps/wa-api/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:137
            .then(() => reject(new boom_1.Boom('Timed Out', {
                               ^

Error: Timed Out
    at /opt/node_apps/wa-api/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:137:32 {
  data: {
    stack: 'Error\n' +
      '    at promiseTimeout (/opt/node_apps/wa-api/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:132:19)\n' +
      '    at waitForMessage (/opt/node_apps/wa-api/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:114:53)\n' +
      '    at query (/opt/node_apps/wa-api/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:136:22)\n' +
      '    at getAvailablePreKeysOnServer (/opt/node_apps/wa-api/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:179:30)\n' +
      '    at uploadPreKeysToServerIfRequired (/opt/node_apps/wa-api/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:205:35)\n' +
      '    at WebSocketClient.<anonymous> (/opt/node_apps/wa-api/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:492:15)\n' +
      '    at WebSocketClient.emit (node:events:513:28)\n' +
      '    at /opt/node_apps/wa-api/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:236:35\n' +
      '    at Object.decodeFrame (/opt/node_apps/wa-api/node_modules/@whiskeysockets/baileys/lib/Utils/noise-handler.js:136:17)\n' +
      '    at WebSocketClient.onMessageRecieved (/opt/node_apps/wa-api/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:212:15)'
  },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 408,
    payload: {
      statusCode: 408,
      error: 'Request Time-out',
      message: 'Timed Out'
    },
    headers: {}
  }
}
/opt/node_apps/wa-api/node_modules/mongodb/lib/cmap/connect.js:381
            return new error_1.MongoNetworkTimeoutError('connection timed out');
                   ^

MongoNetworkTimeoutError: connection timed out
    at connectionFailureError (/opt/node_apps/wa-api/node_modules/mongodb/lib/cmap/connect.js:381:20)
    at TLSSocket.<anonymous> (/opt/node_apps/wa-api/node_modules/mongodb/lib/cmap/connect.js:285:22)
    at Object.onceWrapper (node:events:627:28)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.Socket._onTimeout (node:net:550:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  connectionGeneration: 5,
  [Symbol(errorLabels)]: Set(0) {},
  [cause]: undefined
}

**Comment by mdestafadilah** [comment]
```yarn``` or ```npm``` to installing packages?
